### ISSUE TITLE
Plugin should be updated to last json API and use https.

### ISSUE THREAD

**Issue by Tki2000** [zak-45/Broadlink-Domoticz-plugin#2]
I have tried to install the plugin under Ubuntu Server 22.04 and it fails.

Errors on Ubuntu 22.04 Server and how to solve them.

There are errors in the installation script that makes installation on an Ubuntu 22.04 server impossible.
Installations script is using (forcing) protocol http and old json API. It should be updated to https and new json API or the call to language identification be removed. It is almost superflous and breaks things.
Also, python in Ubuntu 22.04 is called by python3 commandline and this script forces call on python (not python3) so all calls will fail on installation.

I can fix the installation by downloading the install script, editing the file and executing it, but it will have problem running on latest Domoticz as it will try to make calls on http to fill the admin pages and will fail miserably. But at least you can access the admin page outside Domoticz and it will (kinda) work.

To install on Ubuntu Server 22.04 : 
mkdir /[domoticz path]/plugins/Broadlink
cd /[domoticz path]/plugins/Broadlink
wget -q -Osetup.py https://raw.githubusercontent.com/zak-45/Broadlink-Domoticz-plugin/main/setup.py

Edit file with a text editor and find "def domlang", put this:

def domlang():
    return "en"

Now find all references to (2 places found)
        command = 'sudo -H python -m pip install ' + mod
Replace with 
        command = 'sudo -H python3 -m pip install ' + mod

Save file and exit

python3 ./setup.py
Put the correct address of Domoticz server and port to communicate. It will install OK.
systemctl stop domoticz
systemctl start domoticz

When a hardware with Broadlink is created it will create a device in Domoticz and a page under "Custom" tab. The page will not display properly because it insists on using http and not https.
You can access that admin page by manually writting the URL directly with http protocol : http://[domoticzip]:9000, http://[domoticzip]:9001, etc, depending on how many hardware items you have added on different listening ports.

If one has to know what language to put on the "def domlang()" function you should do a json call with the new API on https. My Domoticz is denying the http protocol on settings. 
--> https://[domoticzip]:[domoticzport]/json.htm?type=command&param=getsettings --> look for the var "Language" value.
The plugin is currently using a http://[domoticzip]:[domoticzport]/json.htm?type=settings call. Old json API will be eventually obsoleted.

I think this plugin should have an update for making it work on linux systems and not only on "Pi" systems.

**Comment by zak-45** [comment]
Hi, 

no plan for https, this is to used on local/trusted network.
Not necessary to change python to python3 when follow installation guide and put the right python version to be system wide.
But for the API, when got some times, will try to see what could be done.

thanks
